#!/usr/bin/env python

import sys, os
import optparse

if os.path.exists("/cygdrive"):
    # TODO: better cygwin logic
    pathext = [""] + os.getenv("PATHEXT").lower().split(";")
    def correct_case(path):
        segments = path.split("/")
        for i in range(1, len(segments)):
            goals = set(segments[i].lower() + ext for ext in pathext)
            for name in os.listdir("/".join(segments[0:i])+"/"):
                if name.lower() in goals:
                    segments[i] = name
                    break
            else:
                raise WTF
        return "/".join(segments)
else:
    correct_case = lambda path: path

def main(args):
    if args == []:
        args = ["."]
    for arg in args:
        print(correct_case(os.path.abspath(arg)))

if __name__ == "__main__":
    parser = optparse.OptionParser(usage="usage: %prog [options] [args...]")
    (options, args) = parser.parse_args()
    sys.exit(main(args))

