#!/usr/bin/env python3

import sys, os

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("file", nargs="*")
    args = parser.parse_args()
    files = args.file or ["."]

    for file in files:
        print(os.path.abspath(file))

if __name__ == "__main__":
    main()
