#!/usr/bin/env python

__doc__ = "like grep, but prints the captured group instead of the whole match."

import sys, re

def read_file(path):
    with open(path) as file_handle:
        return file_handle.read()

def main(pattern_str, args):
    pattern = re.compile(pattern_str, re.MULTILINE)
    if len(args) == 0:
        args = ["-"]
    result = []
    for file_path in args:
        if file_path == "-":
            input_content = sys.stdin.read()
        else:
            input_content = read_file(file_path)
        result.extend(pattern.findall(input_content))
    sys.stdout.write("\n".join(result))
    sys.stdout.write("\n")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(__doc__, version="0.0")
    parser.add_argument("pattern", help="re.compile(pattern, re.MULTILINE)")
    parser.add_argument("file", nargs="*", help="default is -. - is stdin.")

    args = parser.parse_args()
    sys.exit(main(args.pattern, args.file))
