#!/usr/bin/env python3

import os, sys, time
import subprocess

__version__ = "0.2"
usage = """
Usage: %(prog)s [-t n] [--] command...

Executes command repeatedly forever.

Options:
  -t n           wait for n seconds between invocations. default is 1.0.

Version: %(version)s

Example: %(prog)s du -b error.log
""" % {
    "prog": os.path.split(os.path.abspath(sys.argv[0]))[1],
    "version": __version__,
}

def main():
    seconds = 1
    # no argparse, because we're forwarding arbitrary subcommands
    args = sys.argv[1:]
    if len(args) >= 2 and args[0] == "-t":
        seconds = float(args[1])
        del args[:2]
    if len(args) >= 1:
        if args[0] == "--":
            # if your command actually begins with -, then prefix it with a -- arg.
            del args[0]
        elif args[0].startswith("-"):
            # such as --help or any other unrecognized command
            sys.exit(usage)
    if len(args) == 0:
        sys.exit(usage)
    cmd = args
    try:
        while True:
            subprocess.call(cmd)
            time.sleep(seconds)
    except KeyboardInterrupt:
        print("")

if __name__ == "__main__":
    main()
