#!/usr/bin/env python
import sys
import gtk
clipboard = gtk.clipboard_get()
if sys.argv[1:] == ["-p"]:
    sys.stdout.write(clipboard.wait_for_text())
else:
    clipboard.set_text(sys.stdin.read())
    clipboard.store()
