#!/usr/bin/env python3

"""
Sorts files in place. Assumes unix line endings.
If the file does not end with a LF, then an LF will be added before sorting.
"""

import sys, os

def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("file", nargs="+")
    parser.add_argument("-u", "--unique", action="store_true", help=
        "Eliminate duplicates.")
    args = parser.parse_args()

    for path in args.file:
        with open(path) as f:
            lines = list(f)
        if len(lines) > 0 and not lines[-1].endswith("\n"):
            # can't handle missing an EOL at the end of the file
            lines[-1] += "\n"
        if args.unique:
            lines = list(set(lines))
        lines.sort()
        with open(path, "w") as f:
            f.write("".join(lines))

if __name__ == "__main__":
    main()
